<?php
declare(strict_types=1);
final class ReportRepository extends Repository
{
    public function overview(array $filters=[]): array {
        $where=[];$params=[];if(!empty($filters['program_id'])){$where[]='s.program_id=?';$params[]=$filters['program_id'];}if(!empty($filters['status'])){$where[]='s.status=?';$params[]=$filters['status'];}$whereSql=$where?' WHERE '.implode(' AND ',$where):'';
        $st=$this->db()->prepare("SELECT p.name,COUNT(s.id) total FROM programs p LEFT JOIN students s ON s.program_id=p.id".($where?' AND '.implode(' AND ',$where):'')." GROUP BY p.id,p.name ORDER BY total DESC,p.name");$st->execute($params);$studentsByProgram=$st->fetchAll();
        $applications=$this->db()->query('SELECT status,COUNT(*) total FROM applications GROUP BY status ORDER BY total DESC')->fetchAll();$theses=$this->db()->query('SELECT status,COUNT(*) total FROM theses GROUP BY status ORDER BY total DESC')->fetchAll();$studentsByStatus=$this->db()->query('SELECT status,COUNT(*) total FROM students GROUP BY status ORDER BY total DESC')->fetchAll();$research=$this->db()->query('SELECT status,COUNT(*) total FROM research_proposals GROUP BY status ORDER BY total DESC')->fetchAll();$gpa=$this->db()->query("SELECT AVG(x.gpa) FROM (SELECT sc.student_id, SUM(CASE WHEN sc.grade IS NOT NULL THEN sc.grade*c.credits ELSE 0 END)/NULLIF(SUM(CASE WHEN sc.grade IS NOT NULL THEN c.credits ELSE 0 END),0) gpa FROM student_courses sc JOIN courses c ON c.id=sc.course_id GROUP BY sc.student_id) x")->fetchColumn();return ['students'=>$studentsByProgram,'applications'=>$applications,'theses'=>$theses,'student_status'=>$studentsByStatus,'research'=>$research,'average_gpa'=>round((float)$gpa,2)];
    }
    public function studentsReport(array $filters=[]): array { $where=[];$params=[];if(!empty($filters['program_id'])){$where[]='s.program_id=?';$params[]=$filters['program_id'];}if(!empty($filters['status'])){$where[]='s.status=?';$params[]=$filters['status'];}$sql="SELECT s.student_no,s.full_name,p.name program_name,s.status,COALESCE((SELECT SUM(c.credits) FROM student_courses sc JOIN courses c ON c.id=sc.course_id WHERE sc.student_id=s.id AND sc.status='PASSED'),0) earned_credits,COALESCE((SELECT SUM(sc.grade*c.credits)/NULLIF(SUM(c.credits),0) FROM student_courses sc JOIN courses c ON c.id=sc.course_id WHERE sc.student_id=s.id AND sc.grade IS NOT NULL),0) gpa FROM students s JOIN programs p ON p.id=s.program_id".($where?' WHERE '.implode(' AND ',$where):'')." ORDER BY s.full_name";$st=$this->db()->prepare($sql);$st->execute($params);return $st->fetchAll(); }
}
